changing squares keys
pashunt13/tic-tac-toe pull request #1
Opened 2023-05-03 19:29 UTC by pashunt13

2023-05-03 19:43 UTC, pashunt13 commented on src/Board.js
> +    console.log(squares);
вот тут дикий прикол случается, если пробовать переписать с двухмерныйм массивом. лог выводит массив в первый раз после клика уже заполненный до того как сработает условие, которое ниже и должно его заполнить. при этом заполняется не одно поле, а целая строка, то есть три

2023-05-08 16:26 UTC, tikijian requested changes

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
> +    const lines = [
выносим в константу

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
>    let winPoints = [];
лишняя переменная

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
>    if (winner) {
Это тоже можно обернуть в useMemo, который вычисляет status, уже в зависимости от [xIsNext, winner]

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
> +    status = `Draw`;
здесь нет интерполяции, можно обычные кавычки

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
> +      const nextSquares = squares.slice();
если тебе нужен клон массива, то лучше читается `Array.from(squares)`

2023-05-08 16:26 UTC, tikijian commented on src/Board.js
> +      if (xIsNext) {
эту простыню можно заменить на тернарник

2023-05-08 16:26 UTC, tikijian commented on src/Square.js
> +  const className = classNames({
если sqare есть всегда, а win меняется, то используют такую форму:
```
classNames('square', { win: isWinSquare } )
```

2023-05-09 15:59 UTC, tikijian requested changes

2023-05-09 15:59 UTC, tikijian commented on src/Board.js
> +  const status = useMemo(() => {
красиво юзать gurd expressions (он же early return). Тогда и остальное сократится

```
if (!winner) {
  return `Next player: ${xIsNext ? "X" : "O"}`;
}

return winner ? `Winner: ${winner}` : "Draw";
```

2023-05-09 15:59 UTC, tikijian commented on src/Board.js
> +    if (!squares.includes(null)) {
так и не перенес в начало функции

2023-05-09 15:59 UTC, tikijian commented on src/Square.js
> +  const className = classNames("square", { "square win": isWinSquare });
я не так написал

2023-08-09 23:24 UTC, merged